### ISSUE TITLE
Рекомендуется добавить визуальную верификацию и вывод

### ISSUE THREAD

**Issue by l1806858547** [kalenchukov/UserAgentParser#1]
Как и яуаа, он удобен для верификации

**Comment by kalenchukov** [comment]
> Как и яуаа, он удобен для верификации

Ничего не понял. Можно подробней?

**Comment by l1806858547** [comment]
> > Как и яуаа, он удобен для верификации
> 
> Ничего не понял。Можно подробней？

Обратитесь к этому веб-сайту https://try.yauaa.basjes.nl/

**Comment by kalenchukov** [comment]
UserAgentParsing это просто библиотека. Делать для неё веб-интерфейс с выводом не вижу необходимости.
